# todo: detect and rotate upside-down text instead of just converting to text which will then be backwards
import string

# https://www.upsidedowntext.com/unicode
table = {
    "a":     "ɐ (U+0250)<br><span>&amp;#592;</span>",
    "b":     "q",
    "c":     "ɔ (U+0254)<br><span>&amp;#596;</span>",
    "d":     "p",
    "e":     "ǝ (U+01DD)<br><span>&amp;#477;</span>",
    "f":     "ɟ (U+025F)<br><span>&amp;#607;</span>",
    "g":     "ƃ (U+0183)<br><span>&amp;#387;</span>",
    "h":     "ɥ (U+0265)<br><span>&amp;#613;</span>",
    "i":     "ᴉ (U+1D09)<br><span>&amp;#7433;</span>",
    "j":     "ɾ (U+027E)<br><span>&amp;#638;</span>",
    "k":     "ʞ (U+029E)<br><span>&amp;#670;</span>",
    "l":     "l",
    "m":     "ɯ (U+026F)<br><span>&amp;#623;</span>",
    "n":     "u",
    "o":     "o",
    "p":     "d",
    "q":     "b",
    "r":     "ɹ (U+0279)<br><span>&amp;#633;</span>",
    "s":     "s",
    "t":     "ʇ (U+0287)<br><span>&amp;#647;</span>",
    "u":     "n",
    "v":     "ʌ (U+028C)<br><span>&amp;#652;</span>",
    "w":     "ʍ (U+028D)<br><span>&amp;#653;</span>",
    "x":     "x",
    "y":     "ʎ (U+028E)<br><span>&amp;#654;</span>",
    "z":     "z",
    "A":     "∀ (U+2200)<br><span>&amp;#8704;</span>",
    "B":     "B",
    "C":     "Ɔ (U+0186)<br><span>&amp;#390;</span>",
    "D":     "D",
    "E":     "Ǝ (U+018E)<br><span>&amp;#398;</span>",
    "F":     "Ⅎ (U+2132)<br><span>&amp;#8498;</span>",
    "G":     "פ (U+05E4)<br><span>&amp;#1508;</span>",
    "H":     "H",
    "I":     "I",
    "J":     "ſ (U+017F)<br><span>&amp;#383;</span>",
    "K":     "K",
    "L":     "˥ (U+02E5)<br><span>&amp;#741;</span>",
    "M":     "W",
    "N":     "N",
    "O":     "O",
    "P":     "Ԁ (U+0500)<br><span>&amp;#1280;</span>",
    "Q":     "Q",
    "R":     "R",
    "S":     "S",
    "T":     "┴ (U+2534)<br><span>&amp;#9524;</span>",
    "U":     "∩ (U+2229)<br><span>&amp;#8745;</span>",
    "V":     "Λ (U+039B)<br><span>&amp;#923;</span>",
    "W":     "M",
    "X":     "X",
    "Y":     "⅄ (U+2144)<br><span>&amp;#8516;</span>",
    "Z":     "Z",
    "0":     "0",
    "1":     "Ɩ (U+0196)<br><span>&amp;#406;</span>",
    "2":     "ᄅ (U+1105)<br><span>&amp;#4357;</span>",
    "3":     "Ɛ (U+0190)<br><span>&amp;#400;</span>",
    "4":     "ㄣ (U+3123)<br><span>&amp;#12579;</span>",
    "5":     "ϛ (U+03DB)<br><span>&amp;#987;</span>",
    "6":     "9",
    "7":     "ㄥ (U+3125)<br><span>&amp;#12581;</span>",
    "8":     "8",
    "9":     "6",
    ",":     "'",
    ".":     "˙ (U+02D9)<br><span>&amp;#729;</span>",
    "?":     "¿ (U+00BF)<br><span>&amp;#191;</span>",
    "!":     "¡ (U+00A1)<br><span>&amp;#161;</span>",
    '"':     ",,",
    "'":     ",",
    "`":     ",",
    "(":     ")",
    ")":     "(",
    "[":     "]",
    "]":     "[",
    "{":     "}",
    "}":     "{",
    "&lt;":  "&gt;",
    "&gt;":  "&lt;",
    "&amp;": "⅋ (U+214B)<br><span>&amp;#8523;</span>",
    "_":     "‾ (U+203E)<br><span>&amp;#8254;</span>",
}

# https://github.com/cburgmer/upsidedown/blob/master/upsidedown.py
FLIP_RANGES = [
    (string.ascii_lowercase, "ɐqɔpǝɟƃɥᴉɾʞꞁɯuodbɹsʇnʌʍxʎz"),
    # alternatives: l:ʅ
    (string.ascii_uppercase, "ⱯᗺƆᗡƎᖵ⅁HIᒋ⋊ꞀWNOԀꝹᴚS⊥∩ɅMX⅄Z"),
    # alternatives: L:ᒣ⅂, J:ſ, F:߃Ⅎ, A:∀ᗄ, U:Ⴖ, W:Ϻ, C:ϽↃ, Q:Ό, M:Ɯꟽ
    (string.digits, "0ІᘔƐᔭ59Ɫ86"),
    (string.punctuation, "¡„#$%⅋,)(*+'-˙/:؛>=<¿@]\\[ᵥ‾`}|{~"),
]
UNICODE_COMBINING_DIACRITICS = {'̈': '̤', '̊': '̥', '́': '̗', '̀': '̖',
                                '̇': '̣', '̃': '̰', '̄': '̱', '̂': '̬', '̆': '̯', '̌': '̭',
                                '̑': '̮', '̍': '̩'}

TRANSLITERATIONS = {'ß': 'ss'}

# https://github.com/doherty/Text-UpsideDown/blob/master/lib/Text/UpsideDown.pm
upside_down_map = {
    'A':                                  "\N{FOR ALL}",
    'B':                                  "\N{GREEK SMALL LETTER XI}",
    'C':                                  "\N{ROMAN NUMERAL REVERSED ONE HUNDRED}",
    'D':                                  "\N{LEFT HALF BLACK CIRCLE}",
    'E':                                  "\N{LATIN CAPITAL LETTER REVERSED E}",
    'F':                                  "\N{TURNED CAPITAL F}",
    'G':                                  "\N{TURNED SANS-SERIF CAPITAL G}",
    'J':                                  "\N{LATIN SMALL LETTER LONG S}",
    'K':                                  "\N{RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT}",
    'L':                                  "\N{TURNED SANS-SERIF CAPITAL L}",
    'M':                                  'W',
    'N':                                  "\N{LATIN LETTER SMALL CAPITAL REVERSED N}",
    'P':                                  "\N{CYRILLIC CAPITAL LETTER KOMI DE}",
    'Q':                                  "\N{GREEK CAPITAL LETTER OMICRON WITH TONOS}",
    'R':                                  "\N{LATIN LETTER SMALL CAPITAL TURNED R}",
    'T':                                  "\N{UP TACK}",
    'U':                                  "\N{INTERSECTION}",
    'V':                                  "\N{GREEK LETTER SMALL CAPITAL LAMDA}",
    'Y':                                  "\N{TURNED SANS-SERIF CAPITAL Y}",
    'a':                                  "\N{LATIN SMALL LETTER TURNED A}",
    'b':                                  'q',
    'c':                                  "\N{LATIN SMALL LETTER OPEN O}",
    'd':                                  'p',
    'e':                                  "\N{LATIN SMALL LETTER TURNED E}",
    'f':                                  "\N{LATIN SMALL LETTER DOTLESS J WITH STROKE}",
    'g':                                  "\N{LATIN SMALL LETTER B WITH TOPBAR}",
    'h':                                  "\N{LATIN SMALL LETTER TURNED H}",
    'i':                                  "\N{LATIN SMALL LETTER DOTLESS I}",
    'j':                                  "\N{LATIN SMALL LETTER R WITH FISHHOOK}",
    'k':                                  "\N{LATIN SMALL LETTER TURNED K}",
    'l':                                  "\N{LATIN SMALL LETTER ESH}",
    'm':                                  "\N{LATIN SMALL LETTER TURNED M}",
    'n':                                  'u',
    'r':                                  "\N{LATIN SMALL LETTER TURNED R}",
    't':                                  "\N{LATIN SMALL LETTER TURNED T}",
    'v':                                  "\N{LATIN SMALL LETTER TURNED V}",
    'w':                                  "\N{LATIN SMALL LETTER TURNED W}",
    'y':                                  "\N{LATIN SMALL LETTER TURNED Y}",
    '!':                                  "\N{INVERTED EXCLAMATION MARK}",
    '"':                                  "\N{DOUBLE LOW-9 QUOTATION MARK}",
    '&':                                  "\N{TURNED AMPERSAND}",
    "'":                                  ', ',
    '.':                                  "\N{DOT ABOVE}",
    '^':                                  "\N{LOGICAL OR}",
    '*':                                  "\N{LOW ASTERISK}",
    '1':                                  "\N{DOWNWARDS HARPOON WITH BARB RIGHTWARDS}",
    '3':                                  "\N{LATIN CAPITAL LETTER OPEN E}",
    '6':                                  '9',
    '7':                                  "\N{BOPOMOFO LETTER ENG}",
    ';':                                  "\N{ARABIC SEMICOLON}",
    '?':                                  "\N{INVERTED QUESTION MARK}",
    '(':                                  ')',
    '[':                                  ']',
    '{':                                  '}',
    '<':                                  '>',
    '_':                                  "\N{OVERLINE}",
    "\N{UNDERTIE}":                       "\N{CHARACTER TIE}",
    "\N{LEFT SQUARE BRACKET WITH QUILL}": "\N{RIGHT SQUARE BRACKET WITH QUILL}",
    "\N{THEREFORE}":                      "\N{BECAUSE}",
}

# https://github.com/aaron-em/upside-down.el/blob/master/upside-down.el
upside_down_mapping = {
    # quotes
    "\"": "„",
    "'":  ",",
    # brackets and braces
    "(":  ")",
    ")":  "(",
    "[":  "]",
    "]":  "[",
    "{":  "}",
    "}":  "{",
    "<":  ">",
    ">":  "<",
    # punctuation
    ".":  "˙",
    "_":  "‾",
    "&":  "⅋",
    "!":  "¡",
    ";":  "؛",
    "?":  "¿",
    "-":  "-",
    ",":  "'",
    # majuscules
    "A":  "∀",
    "B":  "ჵ",
    "C":  "Ↄ",
    "D":  "ᗡ",
    "E":  "Ǝ",
    "F":  "Ⅎ",
    "G":  "⅁",
    "H":  "H",
    "I":  "I",
    "J":  "ᒋ",
    "K":  "ʞ",
    "L":  "⅂",
    "M":  "ꟽ",
    "N":  "И",
    "O":  "O",
    "P":  "Ԁ",
    "Q":  "Ό",
    "R":  "ᴚ",
    "S":  "S",
    "T":  "⊥",
    "U":  "∩",
    "V":  "ᴧ",
    "W":  "M",
    "X":  "X",
    "Y":  "⅄",
    "Z":  "Z",
    # minuscules
    "a":  "ɐ",
    "b":  "q",
    "c":  "ɔ",
    "d":  "p",
    "e":  "ǝ",
    "f":  "ɟ",
    "g":  "ƃ",
    "h":  "ɥ",
    "i":  "ⵑ",
    "j":  "ṛ",
    "k":  "ʞ",
    "l":  "ʃ",
    "m":  "ɯ",
    "n":  "u",
    "o":  "o",
    "p":  "d",
    "q":  "b",
    "r":  "ɹ",
    "s":  "s",
    "t":  "ʇ",
    "u":  "n",
    "v":  "ʌ",
    "w":  "ʍ",
    "x":  "x",
    "y":  "ʎ",
    "z":  "z",
    # digits
    "0":  "0",
    "1":  "⥝",
    "2":  "ⵒ",
    "3":  "Ɛ",
    "4":  "ᔭ",
    "5":  "Ϛ",
    "6":  "9",
    "7":  "∠",
    "8":  "8",
    "9":  "6",
}

# somewhere
# """0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~"""
# """~{|}`‾^[\\]@¿<=>؛:/˙-'+*(),\&%$#„¡ZʎXMΛ∩⊥SᴚὉԀONW˥ʞſIHƃℲƎᗡϽq∀zʎxʍʌnʇsɹbdouɯןʞɾıɥƃɟǝpɔqɐ9876543210"""
mapping = {
    'a':  'ɐ',
    'b':  'q',
    'c':  'ɔ',
    'd':  'p',
    'e':  'ǝ',
    'f':  'ɟ',
    'g':  'ƃ',
    'h':  'ɥ',
    'i':  'ı',
    'j':  'ɾ',
    'k':  'ʞ',
    'l':  'ן',
    'm':  'ɯ',
    'n':  'u',
    'o':  'o',
    'p':  'd',
    'q':  'b',
    'r':  'ɹ',
    's':  's',
    't':  'ʇ',
    'u':  'n',
    'v':  'ʌ',
    'w':  'ʍ',
    'x':  'x',
    'y':  'ʎ',
    'z':  'z',
    'A':  '∀',
    'B':  'q',
    'C':  'Ͻ',
    'D':  'ᗡ',
    'E':  'Ǝ',
    'F':  'Ⅎ',
    'G':  'ƃ',
    'H':  'H',
    'I':  'I',
    'J':  'ſ',
    'K':  'ʞ',
    'L':  '˥',
    'M':  'W',
    'N':  'N',
    'O':  'O',
    'P':  'Ԁ',
    'Q':  'Ὁ',
    'R':  'ᴚ',
    'S':  'S',
    'T':  '⊥',
    'U':  '∩',
    'V':  'Λ',
    'W':  'M',
    'X':  'X',
    'Y':  'ʎ',
    'Z':  'Z',
    '!':  '¡',
    '"':  '„',
    '#':  '#',
    '$':  '$',
    '%':  '%',
    '&':  '&',
    "'":  ',',
    '(':  ')',
    ')':  '(',
    '*':  '*',
    '+':  '+',
    ',':  "'",
    '-':  '-',
    '.':  '˙',
    '/':  '/',
    ':':  ':',
    ';':  '؛',
    '<':  '>',
    '=':  '=',
    '>':  '<',
    '?':  '¿',
    '@':  '@',
    '[':  ']',
    '\\': '\\',
    ']':  '[',
    '^':  '^',
    '_':  '‾',
    '`':  '`',
    '{':  '}',
    '|':  '|',
    '}':  '{',
    '~':  '~',
}

# https://www.fileformat.info/convert/text/upside-down-map.htm
table2 = {
    "! - U+0021 EXCLAMATION MARK (U+0021)</a>":               "¡ - U+00a1 INVERTED EXCLAMATION MARK (U+00A1)</a>",
    '" - U+0022 QUOTATION MARK (U+0022)</a>':                 "„ - U+201e DOUBLE LOW-9 QUOTATION MARK (U+201E)</a>",
    "&amp; - U+0026 AMPERSAND (U+0026)</a>":                  "⅋ - U+214b TURNED AMPERSAND (U+214B)</a>",
    "' - U+0027 APOSTROPHE (U+0027)</a>":                     ", - U+002c COMMA (U+002C)</a>",
    "( - U+0028 LEFT PARENTHESIS (U+0028)</a>":               ") - U+0029 RIGHT PARENTHESIS (U+0029)</a>",
    ". - U+002e FULL STOP (U+002E)</a>":                      "˙ - U+02d9 DOT ABOVE (U+02D9)</a>",
    "3 - U+0033 DIGIT THREE (U+0033)</a>":                    "Ɛ - U+0190 LATIN CAPITAL LETTER OPEN E (U+0190)</a>",
    "4 - U+0034 DIGIT FOUR (U+0034)</a>":                     "ᔭ - U+152d CANADIAN SYLLABICS YA (U+152D)</a>",
    "6 - U+0036 DIGIT SIX (U+0036)</a>":                      "9 - U+0039 DIGIT NINE (U+0039)</a>",
    "7 - U+0037 DIGIT SEVEN (U+0037)</a>":                    "Ɫ - U+2c62 LATIN CAPITAL LETTER L WITH MIDDLE TILDE (U+2C62)</a>",
    "; - U+003b SEMICOLON (U+003B)</a>":                      "؛ - U+061b ARABIC SEMICOLON (U+061B)</a>",
    "&lt; - U+003c LESS-THAN SIGN (U+003C)</a>":              "&gt; - U+003e GREATER-THAN SIGN (U+003E)</a>",
    "? - U+003f QUESTION MARK (U+003F)</a>":                  "¿ - U+00bf INVERTED QUESTION MARK (U+00BF)</a>",
    "A - U+0041 LATIN CAPITAL LETTER A (U+0041)</a>":         "∀ - U+2200 FOR ALL (U+2200)</a>",
    "B - U+0042 LATIN CAPITAL LETTER B (U+0042)</a>":         "𐐒 - U+0412 DESERET CAPITAL LETTER BEE (U+10412)</a>",
    "C - U+0043 LATIN CAPITAL LETTER C (U+0043)</a>":         "Ↄ - U+2183 ROMAN NUMERAL REVERSED ONE HUNDRED (U+2183)</a>",
    "D - U+0044 LATIN CAPITAL LETTER D (U+0044)</a>":         "◖ - U+25d6 LEFT HALF BLACK CIRCLE (U+25D6)</a>",
    "E - U+0045 LATIN CAPITAL LETTER E (U+0045)</a>":         "Ǝ - U+018e LATIN CAPITAL LETTER REVERSED E (U+018E)</a>",
    "F - U+0046 LATIN CAPITAL LETTER F (U+0046)</a>":         "Ⅎ - U+2132 TURNED CAPITAL F (U+2132)</a>",
    "G - U+0047 LATIN CAPITAL LETTER G (U+0047)</a>":         "⅁ - U+2141 TURNED SANS-SERIF CAPITAL G (U+2141)</a>",
    "J - U+004a LATIN CAPITAL LETTER J (U+004A)</a>":         "ſ - U+017f LATIN SMALL LETTER LONG S (U+017F)</a>",
    "K - U+004b LATIN CAPITAL LETTER K (U+004B)</a>":         "⋊ - U+22ca RIGHT NORMAL FACTOR SEMIDIRECT PRODUCT (U+22CA)</a>",
    "L - U+004c LATIN CAPITAL LETTER L (U+004C)</a>":         "⅂ - U+2142 TURNED SANS-SERIF CAPITAL L (U+2142)</a>",
    "M - U+004d LATIN CAPITAL LETTER M (U+004D)</a>":         "W - U+0057 LATIN CAPITAL LETTER W (U+0057)</a>",
    "N - U+004e LATIN CAPITAL LETTER N (U+004E)</a>":         "ᴎ - U+1d0e LATIN LETTER SMALL CAPITAL REVERSED N (U+1D0E)</a>",
    "P - U+0050 LATIN CAPITAL LETTER P (U+0050)</a>":         "Ԁ - U+0500 CYRILLIC CAPITAL LETTER KOMI DE (U+0500)</a>",
    "Q - U+0051 LATIN CAPITAL LETTER Q (U+0051)</a>":         "Ό - U+038c GREEK CAPITAL LETTER OMICRON WITH TONOS (U+038C)</a>",
    "R - U+0052 LATIN CAPITAL LETTER R (U+0052)</a>":         "ᴚ - U+1d1a LATIN LETTER SMALL CAPITAL TURNED R (U+1D1A)</a>",
    "T - U+0054 LATIN CAPITAL LETTER T (U+0054)</a>":         "⊥ - U+22a5 UP TACK (U+22A5)</a>",
    "U - U+0055 LATIN CAPITAL LETTER U (U+0055)</a>":         "∩ - U+2229 INTERSECTION (U+2229)</a>",
    "V - U+0056 LATIN CAPITAL LETTER V (U+0056)</a>":         "ᴧ - U+1d27 GREEK LETTER SMALL CAPITAL LAMDA (U+1D27)</a>",
    "Y - U+0059 LATIN CAPITAL LETTER Y (U+0059)</a>":         "⅄ - U+2144 TURNED SANS-SERIF CAPITAL Y (U+2144)</a>",
    "[ - U+005b LEFT SQUARE BRACKET (U+005B)</a>":            "] - U+005d RIGHT SQUARE BRACKET (U+005D)</a>",
    "_ - U+005f LOW LINE (U+005F)</a>":                       "‾ - U+203e OVERLINE (U+203E)</a>",
    "a - U+0061 LATIN SMALL LETTER A (U+0061)</a>":           "ɐ - U+0250 LATIN SMALL LETTER TURNED A (U+0250)</a>",
    "b - U+0062 LATIN SMALL LETTER B (U+0062)</a>":           "q - U+0071 LATIN SMALL LETTER Q (U+0071)</a>",
    "c - U+0063 LATIN SMALL LETTER C (U+0063)</a>":           "ɔ - U+0254 LATIN SMALL LETTER OPEN O (U+0254)</a>",
    "d - U+0064 LATIN SMALL LETTER D (U+0064)</a>":           "p - U+0070 LATIN SMALL LETTER P (U+0070)</a>",
    "e - U+0065 LATIN SMALL LETTER E (U+0065)</a>":           "ǝ - U+01dd LATIN SMALL LETTER TURNED E (U+01DD)</a>",
    "f - U+0066 LATIN SMALL LETTER F (U+0066)</a>":           "ɟ - U+025f LATIN SMALL LETTER DOTLESS J WITH STROKE (U+025F)</a>",
    "g - U+0067 LATIN SMALL LETTER G (U+0067)</a>":           "ƃ - U+0183 LATIN SMALL LETTER B WITH TOPBAR (U+0183)</a>",
    "h - U+0068 LATIN SMALL LETTER H (U+0068)</a>":           "ɥ - U+0265 LATIN SMALL LETTER TURNED H (U+0265)</a>",
    "i - U+0069 LATIN SMALL LETTER I (U+0069)</a>":           "ı - U+0131 LATIN SMALL LETTER DOTLESS I (U+0131)</a>",
    "j - U+006a LATIN SMALL LETTER J (U+006A)</a>":           "ɾ - U+027e LATIN SMALL LETTER R WITH FISHHOOK (U+027E)</a>",
    "k - U+006b LATIN SMALL LETTER K (U+006B)</a>":           "ʞ - U+029e LATIN SMALL LETTER TURNED K (U+029E)</a>",
    "l - U+006c LATIN SMALL LETTER L (U+006C)</a>":           "ʃ - U+0283 LATIN SMALL LETTER ESH (U+0283)</a>",
    "m - U+006d LATIN SMALL LETTER M (U+006D)</a>":           "ɯ - U+026f LATIN SMALL LETTER TURNED M (U+026F)</a>",
    "n - U+006e LATIN SMALL LETTER N (U+006E)</a>":           "u - U+0075 LATIN SMALL LETTER U (U+0075)</a>",
    "r - U+0072 LATIN SMALL LETTER R (U+0072)</a>":           "ɹ - U+0279 LATIN SMALL LETTER TURNED R (U+0279)</a>",
    "t - U+0074 LATIN SMALL LETTER T (U+0074)</a>":           "ʇ - U+0287 LATIN SMALL LETTER TURNED T (U+0287)</a>",
    "v - U+0076 LATIN SMALL LETTER V (U+0076)</a>":           "ʌ - U+028c LATIN SMALL LETTER TURNED V (U+028C)</a>",
    "w - U+0077 LATIN SMALL LETTER W (U+0077)</a>":           "ʍ - U+028d LATIN SMALL LETTER TURNED W (U+028D)</a>",
    "y - U+0079 LATIN SMALL LETTER Y (U+0079)</a>":           "ʎ - U+028e LATIN SMALL LETTER TURNED Y (U+028E)</a>",
    "{ - U+007b LEFT CURLY BRACKET (U+007B)</a>":             "} - U+007d RIGHT CURLY BRACKET (U+007D)</a>",
    "‿ - U+203f UNDERTIE (U+203F)</a>":                       "⁀ - U+2040 CHARACTER TIE (U+2040)</a>",
    "⁅ - U+2045 LEFT SQUARE BRACKET WITH QUILL (U+2045)</a>": "⁆ - U+2046 RIGHT SQUARE BRACKET WITH QUILL (U+2046)</a>",
    "∴ - U+2234 THEREFORE (U+2234)</a>":                      "∵ - U+2235 BECAUSE (U+2235)</a>",
}
